### ISSUE TITLE
Support for pytorch version: 2.4.1+cu124

### ISSUE THREAD

**Issue by pandayummy** [abus-aikorea/voice-pro#1]
pytorch version: 2.4.1+cu124
expect an upgrade

**Comment by abus-aikorea** [comment]
Your suggestions are very good. We will give priority consideration to your suggestions. We are very concerned about supporting the latest libraries, but it is not easy due to legacy Python pacakges.

**Comment by pandayummy** [comment]
I'm using comfyui, and that requires cu124
https://github.com/comfyanonymous/ComfyUI

![image](https://github.com/user-attachments/assets/92bde1a1-a055-48ae-8021-981c769207b8)

**Comment by bramvera** [comment]
> I'm using comfyui, and that requires cu124 https://github.com/comfyanonymous/ComfyUI
> 
> ![image](https://private-user-images.githubusercontent.com/32961592/374893055-92bde1a1-a055-48ae-8021-981c769207b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NzAyNjIsIm5iZiI6MTcyODQ2OTk2MiwicGF0aCI6Ii8zMjk2MTU5Mi8zNzQ4OTMwNTUtOTJiZGUxYTEtYTA1NS00OGFlLTgwMjEtOTgxYzc2OTIwN2I4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDEwMzI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlYmY1YTdlYTY2MDMzZDc5NTk4ZmNlOWVhYTIxZWI1ZTU0MzUwMmU1Yzc4NWRkY2ViZDEzMzBlOGVmNzYyZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qbAG2gdt0qUyzKjVfMcdPNBB5b0DmrdlXU812Rr4IyI)

it would be better if you installed ComfyUI or Abus on the separated env.

**Comment by abus-aikorea** [comment]
Voice-Pro works in the Python 3.10 & PyTorch 2.5.1+cu121 environment from v1.6.x. 

Additionally, the versions of the main packages in use are as follows:
openai-whisper==20240930
faster-whisper==1.0.3
whisper-timestamped==1.15.5
gradio==4.44.1
torch==2.5.1+cu121
torchvision==0.20.1+cu121
torchaudio==2.5.1+cu121
