### ISSUE TITLE
can not exec 'python -m pip install -r requirements-{app_name}-cpu.txt'

### ISSUE THREAD

**Issue by tohru-shippo** [abus-aikorea/voice-pro#13]
I followed the documentation to install Chocolatey, but I got stuck when running start.bat.

I tried deleting the installer_files and re-running configure.bat, but the issue persists.

The logginng
```
=========================================================================

  ABUS Launcher [Version 3.0]
  contact: abus.aikorea@gmail.com

=========================================================================

Running in 64-bit mode from System32
Current directory: C:\project\ai\voice-pro
Command line:
Miniconda location: C:\project\ai\voice-pro\installer_files\conda
app_name: voice

What is your GPU?

G) NVIDIA GTX, RTX, Tesla
C) CPU (I want to run models in CPU mode)

Input> C
Requirement already satisfied: pip==24.0 in c:\project\ai\voice-pro\installer_files\env\lib\site-packages (24.0)

[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


*******************************************************************
* Installing webui requirements from file: requirements-{app_name}-cpu.txt
*******************************************************************


ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements-{app_name}-cpu.txt'

[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip
Command '"C:\project\ai\voice-pro\installer_files\conda\condabin\conda.bat" activate "C:\project\ai\voice-pro\installer_files\env" >nul && python -m pip install -r requirements-{app_name}-cpu.txt' failed with exit status code '1'.

Exiting now.
Try running the start/update script again.
```

**Comment by abus-aikorea** [comment]
> I followed the documentation to install Chocolatey, but I got stuck when running start.bat.
> 
> I tried deleting the installer_files and re-running configure.bat, but the issue persists.
> 
> The logginng
> 
> ```
> =========================================================================
> 
>   ABUS Launcher [Version 3.0]
>   contact: abus.aikorea@gmail.com
> 
> =========================================================================
> 
> Running in 64-bit mode from System32
> Current directory: C:\project\ai\voice-pro
> Command line:
> Miniconda location: C:\project\ai\voice-pro\installer_files\conda
> app_name: voice
> 
> What is your GPU?
> 
> G) NVIDIA GTX, RTX, Tesla
> C) CPU (I want to run models in CPU mode)
> 
> Input> C
> Requirement already satisfied: pip==24.0 in c:\project\ai\voice-pro\installer_files\env\lib\site-packages (24.0)
> 
> [notice] A new release of pip is available: 24.0 -> 24.3.1
> [notice] To update, run: python.exe -m pip install --upgrade pip
> 
> 
> *******************************************************************
> * Installing webui requirements from file: requirements-{app_name}-cpu.txt
> *******************************************************************
> 
> 
> ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements-{app_name}-cpu.txt'
> 
> [notice] A new release of pip is available: 24.0 -> 24.3.1
> [notice] To update, run: python.exe -m pip install --upgrade pip
> Command '"C:\project\ai\voice-pro\installer_files\conda\condabin\conda.bat" activate "C:\project\ai\voice-pro\installer_files\env" >nul && python -m pip install -r requirements-{app_name}-cpu.txt' failed with exit status code '1'.
> 
> Exiting now.
> Try running the start/update script again.
> ```


Thank you for reporting the error.  
The corrections have been reflected in v1.6.6.
