### ISSUE TITLE
Configure.bat not starting

### ISSUE THREAD

**Issue by Blinnna** [abus-aikorea/voice-pro#15]
Configure.bat not starting

![image](https://github.com/user-attachments/assets/5c0371f7-f89d-440a-b613-c4afaef3f261)

**Comment by Otash360** [comment]
> Configure.bat not starting
> 
> ![image](https://private-user-images.githubusercontent.com/8790596/389022696-5c0371f7-f89d-440a-b613-c4afaef3f261.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyOTU0NDAsIm5iZiI6MTczMjI5NTE0MCwicGF0aCI6Ii84NzkwNTk2LzM4OTAyMjY5Ni01YzAzNzFmNy1mODlkLTQ0MGEtYjYxMy1jNGFmYWVmM2YyNjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjJUMTcwNTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODNkY2I5OWRiODJhNTEwNmYxYTU4MTI3Mzk5NjA1ZjQ4MTE1NWJiY2EwN2IxMjg3YzdiZjU5MWJmYzZmZGViZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.0rBNTWYEtpcO1f5ih9iilPykphQjbmdWIUcmSwav7EM)

Just double-click on **configure.bat** (I noticed the window opened briefly and then closed), and then click on **start.bat**. This will open the command prompt (CMD), and the files will start installing. However, make sure that there are no spaces (" ") in the file names leading up to the **voice-pro** file.

**Comment by Blinnna** [comment]
I manage to start it, but now video file not shown in working area =(. 

https://github.com/user-attachments/assets/b6e599e8-5775-426e-8f59-761067bdd534

**Comment by Otash360** [comment]
> Men uni ishga tushirishga muvaffaq bo'ldim, lekin hozir video fayl ish joyida ko'rsatilmagan =(.
> 
>  chrome_CEIc3ElhPU.mp4

Have you tried restarting the program? Many programs require a restart to resolve certain issues. Please send me the video you're working with, and as a precaution, try restarting the program and testing it again.  

I tested it myself with a video I have, and it worked perfectly fine for me.


![image](https://github.com/user-attachments/assets/20339294-34f5-46c6-b882-d16ace64da0a)

**Comment by Blinnna** [comment]
It is some issue with ffprobe 
![image](https://github.com/user-attachments/assets/da8f53e2-d0e4-4abe-8330-40cd29275d39)

**Comment by Otash360** [comment]
> Bu ffprobe bilan bog'liq muammo ![tasvir](https://private-user-images.githubusercontent.com/8790596/389048510-da8f53e2-d0e4-4abe-8330-40cd29275d39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyOTg5OTksIm5iZiI6MTczMjI5ODY5OSwicGF0aCI6Ii84NzkwNTk2LzM4OTA0ODUxMC1kYThmNTNlMi1kMGU0LTRhYmUtODMzMC00MGNkMjkyNzVkMzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjJUMTgwNDU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGIxMDM5MmExZTY2Y2ZkMjYzNzNmZDRjNGQ5ODM0MDlmOTg3MWYwYThlNjc0OGVkYzlhYmNkM2RmMjUyOTc3ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.PfugnVfvfft_0KMCSyeILnNLDqb0JuJV1KPc1mXhqhU)

You need to install **ffmpeg** and make some changes to your computer's settings. Here's a guide for you. Watch this video fully and try restarting the program afterward: [[Watch the guide here](https://youtu.be/jZLqNocSQDM?si=b4MEGT5RfR5jtfOL)](https://youtu.be/jZLqNocSQDM?si=b4MEGT5RfR5jtfOL).

**Comment by Blinnna** [comment]
Thanks, manage it. Sorry for bothering =)

**Comment by Otash360** [comment]
> Thanks, manage it. Sorry for bothering =)

Aha, I’m happy to use such an amazing program from my dreams and help those who can’t use it. I once wanted to create a program like this, but at that time, I was just starting to learn programming. In short, as a result of my help, were you able to use this program?

**Comment by Blinnna** [comment]
Yes =) thanks it help alot!

**Comment by abus-aikorea** [comment]
Did you reboot your PC after running configure.bat? A reboot is essential for the proper installation of ffmpeg. 
If you encounter any ffmpeg-related issues after rebooting your PC, please refer to the following issue. 

https://github.com/abus-aikorea/voice-pro/issues/4#issuecomment-2467077807
