### ISSUE TITLE
pyd文件是加密过的吗？还有Linux该怎么运行，完全没有方法

### ISSUE THREAD

**Issue by DestoryVIP** [abus-aikorea/voice-pro#3]
首先对该项目的作者表示真挚的感谢！
在复现之余，我发现了有如下问题：
pyd文件是加密过的吗？我看app下有超级多的pyd文件
![image](https://github.com/user-attachments/assets/f4d9b51a-361d-498f-9765-f0da1028efe1)
还有Linux是不是无法运行呢？

**Comment by abus-aikorea** [comment]
您好， @DestoryVIP 

1. 關於pyd檔案：
pyd檔案通常不是加密的。
這些檔案是Python的編譯擴展模組，類似於Windows中使用的動態鏈接庫（.dll）。
但是，由於這些檔案是二進制形式的，因此無法使用普通文本編輯器閱讀。

2. 在Linux上運行：
pyd檔案是Windows專用的，因此無法在Linux上直接運行。
很遺憾，對Linux的支持超出了ABUS的能力範圍。
我們承諾會認真考慮您的建議。謝謝您。
