### ISSUE TITLE
Usage limit (30 minutes)

### ISSUE THREAD

**Issue by JavadZohani** [abus-aikorea/voice-pro#33]
ABUS One-Click AI (Free trial)
Usage limit (30 minutes)
![Screenshot (61)](https://github.com/user-attachments/assets/e81fb66c-ec82-4846-927f-c7cb3c4731dc)

Does this program have any usage restrictions?
If there are any restrictions, please tell us in the description section because why should we install a program with these restrictions?

**Comment by abus-aikorea** [comment]
Hello. I agree with your point. I have revised the README to avoid any misunderstandings regarding the free trial. If you have any additional comments, please feel free to reach out anytime. Thank you.
