### ISSUE TITLE
Hope it works

### ISSUE THREAD

**Issue by terryGUGU** [abus-aikorea/voice-pro#4]
It is hoped that local video translation and subtitle modification functions can be added

**Comment by abus-aikorea** [comment]
Thank you for your suggestion. Subtitle editing is a very challenging task to implement through a web UI. I believe you understand this well. Personally, I rely heavily on SubtitleEdit for subtitle editing.
If you have any other suggestions, they are always welcome. Please feel free to share them. Thank you.

**Comment by HappyHappyPotter** [comment]
ffmpeg can't find
[error    ] [abus:ffmpeg_codec_type] Exception occurred: [WinError 2] 
but i have installed ffmpeg already
what should i do next?

**Comment by abus-aikorea** [comment]
> ffmpeg can't find [error ] [abus:ffmpeg_codec_type] Exception occurred: [WinError 2] but i have installed ffmpeg already what should i do next?

The [WinError 2] error usually occurs when the 'ffprobe' executable file cannot be found. This can happen in the following cases:

1. Main Causes:
- FFmpeg is not installed on the system.
- FFmpeg is installed but not registered in the system's environment variable (PATH).
- FFmpeg is installed in an incorrect path.

2. How to Check:
Try typing ffprobe in the Windows Command Prompt. If FFmpeg is properly installed, you should see the following output.

![20241111_105024](https://github.com/user-attachments/assets/794b5181-bd33-41ef-b6c2-b2ed11e584c0)

3. Solutions:
- Recommended Method:
Run configure.bat for voice-pro. Make sure to reboot the system after the installation is complete.


- Install FFmpeg:
Download from https://ffmpeg.org/download.html for Windows, or use the Chocolatey package manager: choco install ffmpeg.
- Set Environment Variable:
Add the bin folder of the FFmpeg installation directory to the system's environment variable PATH.
Common paths: C:\Program Files\FFmpeg\bin or C:\ffmpeg\bin.

Let me know if you need anything else!

**Comment by HappyHappyPotter** [comment]
Brilliant! it worked after i put ffmpeg in the directoy: C:\ffmpeg\bin.
Thank U so much
