### ISSUE TITLE
下载youtube视频报错

### ISSUE THREAD

**Issue by marmot-joy** [abus-aikorea/voice-pro#8]
下载youtube视频报错
 [error    ] [gradio_gulliver.py] gradio_upload_source - Error transcribing file: ERROR: [youtube] AuOhqsXEOB0: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

**Comment by abus-aikorea** [comment]
> 下载youtube视频报错

感谢您报告错误。
当YouTube要求验证以防止机器人时会出现此错误。如果您使用Chrome浏览器，请在浏览器中访问YouTube并登录。请确认YouTube视频可以在浏览器中正常播放。
如果这个方法无法解决问题，请告诉我。我会寻找其他解决方案。

Thank you for reporting the error.
This error occurs when YouTube requires authentication to prevent bots. 
If you're using Chrome Browser, please access YouTube in your browser and log in. 
Please verify that YouTube videos play normally in your browser.
If this method doesn't resolve the issue, please let me know. 
I'll look for another solution.

**Comment by Otash360** [comment]
Hello,  
I'm encountering this error (I tried twice):  
```
2024-11-13 13:27:34 [error    ] [gradio_gulliver.py] gradio_tts_dubbing - Error transcribing file: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))  
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)  
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>  
Traceback (most recent call last):  
  File "D:\AI\Voice_pro\voice_pro\installer_files\env\lib\asyncio\events.py", line 80, in _run  
    self._context.run(self._callback, *self._args)  
  File "D:\AI\Voice_pro\voice_pro\installer_files\env\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost  
    self._sock.shutdown(socket.SHUT_RDWR)  
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host  
2024-11-13 13:40:06 [error    ] [gradio_gulliver.py] gradio_tts_dubbing - Error transcribing file: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))  
```

I was trying to dub a 57-minute video in Uzbek, but during the voice generation (or translation process), this error appears, causing the dubbing/translation process to stop.

My computer specifications:  

- RTX 4060  
- 13th Gen Intel(R) Core(TM) i5-13400T 1.30 GHz  
- 32 GB RAM  

The voice language model I am using: UZBEKISTAN-Sardor-Male

![Skrinshot 2024-11-13 143047](https://github.com/user-attachments/assets/2106c567-6a83-4773-a67c-bf93462d55d3)

My usage time hadn’t expired when this error occurred. I’m sending this image as additional information
![Skrinshot 2024-11-13 143520](https://github.com/user-attachments/assets/8303293b-cea9-4a4d-89ba-4f2b15a69023)

**Comment by Otash360** [comment]
And also, please, is it possible for this software to dub the video by uploading an external .srt file instead of creating subtitles itself? Currently, there are some issues when creating subtitles (you can see above the cmd window, the repeating words issue)

**Comment by abus-aikorea** [comment]
> And also, please, is it possible for this software to dub the video by uploading an external .srt file instead of creating subtitles itself? Currently, there are some issues when creating subtitles (you can see above the cmd window, the repeating words issue)

The suggestions you provided have been incorporated into v1.6.3. Now, external subtitles can be used for dubbing. However, drag-and-drop functionality is not yet supported. Thank you for your suggestions.

* Tips for using Whisper
The Turbo model of Whisper is 8 times faster than the Large model. Additionally, faster-whisper is 5 times faster than Whisper.
The tiny model is very insufficient for speech recognition. Using the Large model will eliminate the repetition of words like 'oh, oh, oh, oh'.
